import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import "./globals.css";
import "boxicons/css/boxicons.min.css";
import { DarkModeProvider } from "@/components/darkMode/darkMode";

const oswald = Oswald({ weight: "300", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Syaid Abdurrohman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.className} dark:bg-primaryDark dark:text-white transition-colors`}
      >
        <DarkModeProvider>
          <div className="container text-xl flex w-1/2 justify-center">
            <Sidebar />
            {children}
          </div>
        </DarkModeProvider>
      </body>
    </html>
  );
}
